### ISSUE TITLE
enable addition of non-member contributors to Lab repositories

### ISSUE THREAD

**Issue by heaventwig** [LaboratoryB/camfive#12]
## currently
Venn cannot add contributors to this (or any) Lab project.

## desired functionality 
Any Lab member can add non-Lab-member GitHub users as contributors on any Lab project.

**Comment by Hurricos** [comment]
Fixed by promiting you to an organizational Owner of Laboratory B. I've also verified I can demote you to Member again, which means yes, if you wanted to stage a hostile takeover of Laboratory B's Github account, you could.

Have fun!
