### ISSUE TITLE
Document controller

### ISSUE THREAD

**Issue by Hurricos** [LaboratoryB/camfive#13]
The original CAMFive units came with proprietary controllers (those with a "green pcb", [cite](https://forum.lightburnsoftware.com/t/camfive-with-1st-controller/12495/6)). Likely what we have on our hands here.

Per [here](https://forum.lightburnsoftware.com/t/camfive-laser-and-lightburn-software/10450/4), *newer* CAMFive lasers use Ruida controllers stock, just with non-stock firmware. We want to examine the labels on the controller (example image below) to [compare with the labels on a Ruida](https://forum.lightburnsoftware.com/t/camfive-laser-and-lightburn-software/10450/6).

![camfive_control_room_examples](https://github.com/user-attachments/assets/5786c1c1-c8a6-4d2b-bc07-f8e073f90dba)

**Comment by Hurricos** [comment]
The original CAMFive units came with proprietary controllers (those with a "green pcb", [cite](https://forum.lightburnsoftware.com/t/camfive-with-1st-controller/12495/6)). Likely what we have on our hands here.

**Comment by Hurricos** [comment]
Per [here](https://forum.lightburnsoftware.com/t/camfive-lasesr-clf-cma-1080k/54067/4), the "fifth" revision of controllers that CAMFive talks about are the version they started using Ruida. Before then, it was all their proprietary, green-PCB stuff.

This cutter was manufactured 2012; I've seen CMA1080Ks with 2014-or-so manufacturing dates; read as, we almost certainly have the "first" controller.

**Comment by Hurricos** [comment]
![controls_disorder](https://github.com/user-attachments/assets/38074a44-17a3-4c1d-b323-5104fe51dfce)

**Comment by Hurricos** [comment]
@heaventwig Can we get that close-up photo you took, of the laser controller on the left?

**Comment by heaventwig** [comment]
Here they are. Lmk if you want more photos, they're easy to get...
![image](https://github.com/user-attachments/assets/7069c5bf-fe3f-47d5-88d1-af3fddf9c964)
![image](https://github.com/user-attachments/assets/36e749af-31e0-41e4-8829-9bef475591ce)
![image](https://github.com/user-attachments/assets/c4834f41-89e0-4490-97c5-0ad36a6c537f)
![image](https://github.com/user-attachments/assets/29bd944a-968b-481e-97d8-2dd08e90bcb9)
![image](https://github.com/user-attachments/assets/8f94aa4b-e51f-4cf1-bb0f-231a246bd283)
