### ISSUE TITLE
Potentiometer: replace

### ISSUE THREAD

**Issue by heaventwig** [LaboratoryB/camfive#14]
## existing part
![image](https://github.com/user-attachments/assets/181db0a1-b9ae-4710-90ee-9b2fe5bcd5bc)

## existing functionality
- Potentiometer allows current long enough to pulse the laser in tiny bursts (probably milliseconds).
- pot clicks when dial is rotated

## desired functionality
- Match specified resistances r_1 and r_2 
- Match specified input and output voltage tolerances 
- 

## acceptable alternative for testing
- match minimum throughput resistance

**Comment by heaventwig** [comment]
Need to know: what are the specs on this busted potentiometer?

**Comment by DaBlender** [comment]
https://www.amazon.com/RV24YN20S-Potentiometer-Inverter-Regulation-Control/dp/B074KGJ7N6/ref=asc_df_B074KGJ7N6/?tag=hyprod-20&linkCode=df0&hvadid=693270340071&hvpos=&hvnetw=g&hvrand=16507500798411960162&hvpone=&hvptwo=&hvqmt=&hvdev=m&hvdvcmdl=&hvlocint=&hvlocphy=9003007&hvtargid=pla-573197392519&psc=1&mcid=cf56b4f824353650915860538276af43

**Comment by heaventwig** [comment]
Specifically RV24YN 20S B102 12A 1kΩ

**Comment by heaventwig** [comment]
Will look for it in the Lab collection of pots tonight. If not present, I will order it.

**Comment by Hurricos** [comment]
[Page 7 of this PDF](https://www.potentiometers.com/pdf/Tocos_RV24.pdf#page=7) for the decoding of that part code.

B102: `10`E(`2`+1) ohms; B means linear taper. All units taper from 1K0 down to 3R0.

**Comment by heaventwig** [comment]
Cool. Looks like the rest of the RV24YN 20S decodes to
- RV: carbon film resistance element 
- 24: 24mm diameter
- Y: operating range -10°C to +85°C
- N: panel mount, single unit, single shaft, right-angle ear-lug terminals
- 20: 20mm FMS shaft length
- S: slotted shaft end

And we know what 12A means.

I'm satisfied we know what this thing is well enough to replace it.

**Comment by Hurricos** [comment]
> 12A

12A does not here mean that it's rated for 12A. The pot's rated for 0.25W continuous per that sheet. If the mechanical fitment is exact you should replace like-for-like, but the wires suggest it isn't an exact fit.

Please bring the old pot to the Lab. I have a suspicion it still works, and there's something else the matter.

Update: Looked through the Lab's supply of pots. We have some [3610S-1-103](https://www.bourns.com/docs/Product-Datasheets/3610.pdf)'s that'll work electrically: they're rated for higher wattage and have roughly the same dial range degree-for-degree; they just go up to 10K instead of 1K.

**Comment by heaventwig** [comment]
> 12A does not here mean that it's rated for 12A.

Good catch! Do you know what it *does* mean, though?

**Comment by DaBlender** [comment]
Testing with a multimeter it’s overload until a turn audibly and physically
clicks, then some spikes though for a second max. I’m not sure it’s worth
pulling apart to repair wiper or track when new ones are about $10. I’d
rather not rely on a fixed piece but won’t hold up exploration. Maybe it’s
simple and if $10 is prohibitive I can order this weekend.

**Comment by heaventwig** [comment]
New pot ordered. Due to arrive Thursday Sept 26.

**Comment by heaventwig** [comment]
Replacement potentiometer has arrived.

**Comment by heaventwig** [comment]
New potentiometer is installed.

**Comment by heaventwig** [comment]
![image](https://github.com/user-attachments/assets/c9d16f08-3f40-4957-a8a7-9ed8cbfa27c9)

![image](https://github.com/user-attachments/assets/fe172445-dfd9-4759-ab95-33b7c858f5d9)

![image](https://github.com/user-attachments/assets/35785e1e-272d-495f-8e6b-8b47745bdca4)
