### ISSUE TITLE
Outlets: assemble per spec

### ISSUE THREAD

**Issue by Hurricos** [LaboratoryB/camfive#3]
[Here's what](https://laboratoryb.github.io/camfive/docs/Laser_Machine_INSTALLATION_MANUAL.pdf#page=2) the documentation requires.

![image](https://github.com/user-attachments/assets/a0aab970-190b-4369-ae71-649092de1f61)

We've acquired all components needed and are yet to finish assembly.

**Comment by heaventwig** [comment]
![image](https://github.com/user-attachments/assets/7e38e69e-dd2a-4402-942c-eee83aba76aa)
