### ISSUE TITLE
Chiller and coolant: check refrigerant, fill reservoir, test coolant flow

### ISSUE THREAD

**Issue by Hurricos** [LaboratoryB/camfive#4]
The seller appears to have the chiller.

Venn has on their shopping list 2gal of distilled water -- the chiller calls for 1.5 gallons (per [here](https://laboratoryb.github.io/camfive/docs/Laser_Machine_INSTALLATION_MANUAL.pdf#page=5)).

## Installation

See [page 14](https://laboratoryb.github.io/camfive/docs/Laser_Machine_INSTALLATION_MANUAL.pdf#page=14).

## Testing?

We need to make sure coolant flows (and does not leak) before we fire the laser.

## installation manual description
The external water chiller is shown below.
![image](https://github.com/user-attachments/assets/cc26cb38-210d-4e5f-b520-39c7f4cf8b24)

The Chiller comes with two hoses that will be connected to the main assembly for continuous water circulation to keep the laser tube at optimum working temperature. Regularly about 18 °C to 25 °C depending on the environment temperature. Distilled water will be required (1.5 gallons).

**Comment by heaventwig** [comment]
![image](https://github.com/user-attachments/assets/6a73874b-0a77-4000-965b-a5425c5291df)
Liquid coolant is in my cart.

**Comment by Hurricos** [comment]
I neglected to bring the Lab's chiller -- mostly as a convenience irk of moving the thing.

If the stock chiller does not work, we can certainly snag the old pump-and-bucket from the Lab which we used to use to chill the K40.

**Comment by DaBlender** [comment]
Chiller is chilling. Might flush and clean. I briefly saw co2 laser tube antifreeze
