### ISSUE TITLE
power supply: inspect

### ISSUE THREAD

**Issue by heaventwig** [LaboratoryB/camfive#7]
Should be in a compartment in rear of main assembly. "A 750 Watts power supply will be producing the required power for the tube during normal operation. This unit is installed in compartment in the back of the main assembly. The input power is 220 Vac +/- 10% with an output power of 40 kV DC 30 mA."

**Comment by Hurricos** [comment]
Also complete #9.

**Comment by Hurricos** [comment]
The supply is within the unit. I'm certain we all agree this supply is to spec.
