### ISSUE TITLE
main cabinet electronics: inspect

### ISSUE THREAD

**Issue by heaventwig** [LaboratoryB/camfive#8]
"The picture below shows the electronics inside the main cabinet."

![image](https://github.com/user-attachments/assets/5103627a-5add-4bdc-a146-5276e04063f1)

**Comment by Hurricos** [comment]
![controls_disorder](https://github.com/user-attachments/assets/645cdf52-3316-48ee-bf2b-501ec1088922)

**Comment by Hurricos** [comment]
We've inspected the cabinet; appears to agree.
