### ISSUE TITLE
voltage-regulator: inspect; note model number

### ISSUE THREAD

**Issue by heaventwig** [LaboratoryB/camfive#9]
"A voltage regulator is integrated inside the machine to provide power stability.

![image](https://github.com/user-attachments/assets/773ac95f-9529-44cf-803a-b5e855610931)

This particular model is the SVC-3000 VA. We also have SVC-2000 VA and SVC-5000 VA depending on the model. This units are designed to maintain a stable and continous 220 V ac output to keep the electronics running at optimun condition. It protects from power surges, low and high input voltage."

**Comment by Hurricos** [comment]
Heads up: clearly, the voltage regulator is potentially a mechanically separate unit:

![image](https://github.com/user-attachments/assets/5fb5d5b2-47ab-48d6-8a7c-5ad9fb22c1ef)

That photo's from [this eBay listing](https://www.ebay.com/itm/176569390647).

Anyways, that conflicts with the documentation's wording:

> A voltage regulator is **integrated inside the machine** to provide power stability.

**Comment by Hurricos** [comment]
Should be compiled into #7.
